bonfireRecipe:
  key: 'bonfire:bonfire'
  ingredients:
    items:
      S:
        type: STICK
    configuration: |-
      SSS
      SSS
      SSS
  result:
    type: CAMPFIRE
    amount: 1
    custom-model-data: 1
    display-name: §aBonfire
maxPlayerCount: 4