bonfireRecipe:
  key: 'bonfire:bonfire'
  ingredients:
    items:
      S:
        type: STICK
    configuration: |-
      SSS
      SSS
      SSS
  result:
    type: CAMPFIRE
    amount: 1
    custom-model-data: 1
    display-name: §aBonfire
maxPlayerCount: 4
bonfireExpirationTime: 1m
expirationCheckInterval: 10s
respawnSetSound:
  sound: block.ladder.step
  volume: 1f
  pitch: 1.5f
respawnUnsetSound:
  sound: block.ladder.step
  volume: 1f
  pitch: 0.5f
minFallDist: 3