name: Bonfire
version: "${plugin_version}"
main: com.mineinabyss.bonfire.BonfirePlugin
api-version: "1.21"
authors: [ boy0000, Scyu_, Norazan, Ru_Kira ]

permissions:
  bonfire.*:
    description: Gives access to all commands and allows staff to remove bonfires
    children:
      bonfire.remove: true
  bonfire.remove:
    description: Allow staff to remove bonfires.
    default: op

dependencies:
  server:
    Geary:
      required: true
      load: BEFORE
      join-classpath: true
    Blocky:
      required: true
      load: BEFORE
      join-classpath: true
    DeeperWorld:
      required: false
      load: BEFORE
      join-classpath: true
