[versions]
geary = "0.16.100"
mobzy = "0.16.73"
looty = "0.7.56"
deeperworld = "0.5.77"

[libraries]
protocolburrito = "com.mineinabyss:protocolburrito:0.4.33"

geary-papermc-core = { module = "com.mineinabyss:geary-papermc-core", version.ref = "geary" }
looty = { module = "com.mineinabyss:looty", version.ref = "looty" }
deeperworld = { module = "com.mineinabyss:deeperworld", version.ref = "deeperworld" }
