[versions]
geary = "0.19.107"
mobzy = "0.17.78"
looty = "0.7.58"
deeperworld = "0.5.78"

[libraries]
protocolburrito = "com.mineinabyss:protocolburrito:0.4.33"

geary-papermc-core = { module = "com.mineinabyss:geary-papermc-core", version.ref = "geary" }
looty = { module = "com.mineinabyss:looty", version.ref = "looty" }
deeperworld = { module = "com.mineinabyss:deeperworld", version.ref = "deeperworld" }
