[versions]
geary = "0.18.105"
mobzy = "0.17.77"
looty = "0.7.57"
deeperworld = "0.5.77"

[libraries]
protocolburrito = "com.mineinabyss:protocolburrito:0.4.33"

geary-papermc-core = { module = "com.mineinabyss:geary-papermc-core", version.ref = "geary" }
looty = { module = "com.mineinabyss:looty", version.ref = "looty" }
deeperworld = { module = "com.mineinabyss:deeperworld", version.ref = "deeperworld" }
