[versions]
gearyPaper = "0.24-SNAPSHOT"
deeperworld = "0.7.6"
blocky = "0.6.3"
offlineManager = "3.1.2"

[libraries]
geary-papermc = { module = "com.mineinabyss:geary-papermc", version.ref = "gearyPaper" }
deeperworld = { module = "com.mineinabyss:deeperworld", version.ref = "deeperworld" }
blocky = { module = "com.mineinabyss:blocky", version.ref = "blocky" }
offlineManager = { module = "net.quazar.offlinemanager:api", version.ref = "offlineManager" }
