[versions]
geary = "0.19.108"
mobzy = "0.18.79"
looty = "0.8.59"
deeperworld = "0.6.79"

[libraries]
protocolburrito = "com.mineinabyss:protocolburrito:0.5.34"

geary-papermc-core = { module = "com.mineinabyss:geary-papermc-core", version.ref = "geary" }
looty = { module = "com.mineinabyss:looty", version.ref = "looty" }
deeperworld = { module = "com.mineinabyss:deeperworld", version.ref = "deeperworld" }
