[versions]
gearyPaper = "0.24-SNAPSHOT"
deeperworld = "0.7.6"

[libraries]
geary-papermc = { module = "com.mineinabyss:geary-papermc", version.ref = "gearyPaper" }
deeperworld = { module = "com.mineinabyss:deeperworld", version.ref = "deeperworld" }
