[versions]
geary = "0.19.113"
mobzy = "0.18.84"
looty = "0.8.67"
deeperworld = "0.6.82"
protocolburrito = "0.5.37"

[libraries]
protocolburrito = { module = "com.mineinabyss:protocolburrito", version.ref = "protocolburrito" }
geary-papermc-core = { module = "com.mineinabyss:geary-papermc-core", version.ref = "geary" }
looty = { module = "com.mineinabyss:looty", version.ref = "looty" }
deeperworld = { module = "com.mineinabyss:deeperworld", version.ref = "deeperworld" }
