[versions]
gearyPaper = "0.31.0"
blocky = "0.10.15"

[libraries]
geary-papermc = { module = "com.mineinabyss:geary-papermc", version.ref = "gearyPaper" }
blocky = { module = "com.mineinabyss:blocky", version.ref = "blocky" }
minecraft-plugin-axiompaper = "com.moulberry:axiom:4.0.1"
