[versions]
gearyPaper = "0.30.1-dev.10"
blocky = "0.9.13-dev.6"

[libraries]
geary-papermc = { module = "com.mineinabyss:geary-papermc", version.ref = "gearyPaper" }
blocky = { module = "com.mineinabyss:blocky", version.ref = "blocky" }
